name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - navigation
          - all

jobs:
  magento-run-tests:
    runs-on: ubuntu-latest
    name: Run Magento Autotests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: run navigation tests
        if: "github.event.inputs.deployment_target == 'navigation'"
        run: pytest -m navigation --alluredir=allure-results
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
         sudo wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
         sudo tar -zxvf allure-2.34.1.tgz -C /opt
         sudo ln -s /opt/allure-2.34.1/bin/allure /usr/bin/allure
      - name: Generate report
        run: allure generate -c allure-results -o -site
      - name: Save allure report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1
          
  publish-report:
   name: Report publication
   runs-on: ubuntu-latest
   needs: magento-run-tests
   steps:
     - name: Download artifacts
       uses: actions/download-artifact@v4
     - name: Upload Pages artifact
       uses: actions/upload-pages-artifact@v3
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v4.0.5
        
   
  
        
